import type { Config } from "tailwindcss";

const config = {
  darkMode: ["class"],
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      colors: {
        secondary: "var(--color-secondary)",
        "outline-variant": "var(--color-outline-variant)",
        "on-tertiary-fixed-variant": "var(--color-on-tertiary-fixed-variant)",
        "on-background": "var(--color-on-background)",
        "on-surface": "var(--color-on-surface)",
        background: "var(--color-background)",
        "on-primary": "var(--color-on-primary)",
        "primary-container": "var(--color-primary-container)",
        "surface-tint": "var(--color-surface-tint)",
        "surface-dim": "var(--color-surface-dim)",
        tertiary: "var(--color-tertiary)",
        "surface-container": "var(--color-surface-container)",
        "on-primary-container": "var(--color-on-primary-container)",
        "on-surface-variant": "var(--color-on-surface-variant)",
        surface: "var(--color-surface)",
        "surface-container-low": "var(--color-surface-container-low)",
        "tertiary-fixed": "var(--color-tertiary-fixed)",
        "on-tertiary": "var(--color-on-tertiary)",
        "inverse-primary": "var(--color-inverse-primary)",
        "on-primary-fixed-variant": "var(--color-on-primary-fixed-variant)",
        "secondary-fixed-dim": "var(--color-secondary-fixed-dim)",
        "on-secondary-fixed": "var(--color-on-secondary-fixed)",
        "surface-container-lowest": "var(--color-surface-container-lowest)",
        "on-secondary-container": "var(--color-on-secondary-container)",
        "on-error-container": "var(--color-on-error-container)",
        "surface-variant": "var(--color-surface-variant)",
        "inverse-on-surface": "var(--color-inverse-on-surface)",
        "tertiary-fixed-dim": "var(--color-tertiary-fixed-dim)",
        "secondary-container": "var(--color-secondary-container)",
        "tertiary-container": "var(--color-tertiary-container)",
        "on-secondary-fixed-variant": "var(--color-on-secondary-fixed-variant)",
        "surface-bright": "var(--color-surface-bright)",
        "on-secondary": "var(--color-on-secondary)",
        "surface-container-high": "var(--color-surface-container-high)",
        "inverse-surface": "var(--color-inverse-surface)",
        primary: "var(--color-primary)",
        "primary-fixed": "var(--color-primary-fixed)",
        "on-primary-fixed": "var(--color-on-primary-fixed)",
        outline: "var(--color-outline)",
        "on-tertiary-container": "var(--color-on-tertiary-container)",
        "secondary-fixed": "var(--color-secondary-fixed)",
        error: "var(--color-error)",
        "error-container": "var(--color-error-container)",
        "on-error": "var(--color-on-error)",
        "surface-container-highest": "var(--color-surface-container-highest)",
        "primary-fixed-dim": "var(--color-primary-fixed-dim)",
        "on-tertiary-fixed": "var(--color-on-tertiary-fixed)",
        // Shadcn defaults compatibility
        border: "var(--color-outline-variant)",
        input: "var(--color-surface-container-low)",
        ring: "var(--color-primary)",
        foreground: "var(--color-on-background)",
        muted: {
          DEFAULT: "var(--color-surface-variant)",
          foreground: "var(--color-on-surface-variant)",
        },
        accent: {
          DEFAULT: "var(--color-surface-variant)",
          foreground: "var(--color-on-surface)",
        },
        popover: {
          DEFAULT: "var(--color-surface-container-highest)",
          foreground: "var(--color-on-surface)",
        },
        card: {
          DEFAULT: "var(--color-surface-container)",
          foreground: "var(--color-on-surface)",
        },
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        sm: "0.25rem",
        md: "0.75rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        brand: "28px",
        full: "9999px",
      },
      spacing: {
        gutter: "24px",
        "container-max-width": "1280px",
        "margin-mobile": "20px",
        "margin-desktop": "64px",
        unit: "8px",
      },
      fontFamily: {
        "body-lg": ["var(--font-hanken-grotesk)", "sans-serif"],
        "display-hero": ["var(--font-bodoni-moda)", "serif"],
        "title-md": ["var(--font-hanken-grotesk)", "sans-serif"],
        "label-caps": ["var(--font-hanken-grotesk)", "sans-serif"],
        "headline-lg-mobile": ["var(--font-bodoni-moda)", "serif"],
        "body-sm": ["var(--font-hanken-grotesk)", "sans-serif"],
        "headline-lg": ["var(--font-bodoni-moda)", "serif"],
        mono: ["var(--font-jetbrains-mono)", "monospace"],
      },
      fontSize: {
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "display-hero": ["72px", { lineHeight: "84px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "title-md": ["24px", { lineHeight: "32px", fontWeight: "500" }],
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.1em", fontWeight: "700" }],
        "headline-lg-mobile": ["32px", { lineHeight: "40px", fontWeight: "600" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "headline-lg": ["48px", { lineHeight: "56px", fontWeight: "600" }],
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        shimmer: {
          "100%": {
            transform: "translateX(100%)",
          },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        shimmer: "shimmer 2s infinite",
      },
    },
  },
  plugins: [require("tailwindcss-animate"), require("@tailwindcss/typography"), require("@tailwindcss/forms")],
} satisfies Config;

export default config;
